name: Derpfest KSU for OnePlus-7-Series

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env: 
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "7G"
      CCACHE_HARDLINK: "true"
      
    steps:
      - name: 🚀 Enable ccache to speed the build up
        uses: hendrikmuhs/ccache-action@v1.2
      - name: Remove unnecessary files
        run: |
         sudo rm -rf /opt/ghc
         sudo rm -rf "/usr/local/share/boost"
         sudo rm -rf /usr/share/dotnet
         sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Install dependencies
        run: |
         sudo apt-get update -y 
         sudo apt install gcc-aarch64-linux-gnu -y
         sudo apt install gcc-arm-linux-gnueabi -y
         sudo apt install clang-18 -y
         sudo apt install libelf-dev libarchive-tools lld llvm axel binutils make python3 libssl-dev build-essential bc  bison flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs -y
         sudo apt install openjdk-17-jdk-headless -y
         
         axel -q -n 6 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz
         mkdir clang && tar -zxvf linux-x86-refs_heads_main-clang-r547379.tar.gz -C clang
         
        
      - name: ⚡ Checkout kernel's sourcecode and clone submodules
        run: |
          rm -rf kernel
          git clone --recurse-submodules --depth=1 https://github.com/beingsk5/android_kernel_oneplus_sm8150 kernel -b lineage-23.0
      - name: Add Re:binder support
        run: |
         export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
         cd kernel
         wget https://github.com/Sakion-Team/Re-Kernel/releases/download/modifier/Kernel-Modifier-v4.0.jar
         /usr/lib/jvm/java-17-openjdk-amd64/bin/java -jar ./Kernel-Modifier-v4.0.jar
         cd ..
      - name: 📅 Export date of build
        run: |
          echo "DATE=$(date +%d%m%Y)" >> $GITHUB_ENV
   
      - name: 🔄 Update KernelSU-Next
        run: |
          cd kernel 
          patch -p1 < kernelsu.patch
          patch -p1 < path_umount.patch
          # curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -
          git clone --depth=1 -b n3x7g3n-kernel https://github.com/sidex15/KernelSU-Next.git KernelSU-Next
          cd KernelSU-Next/kernel
          chmod +x setup.sh
          ./setup.sh
          cd ..

      - name: Clone SUSFS (Stable Release Tag)
        run: |
          git clone --depth 1 --branch kernel-4.14 https://gitlab.com/simonpunk/susfs4ksu.git susfs4ksu

      - name: Apply SUSFS Patches Automatically
        run: |
          set -e

          KERNEL_ROOT="${GITHUB_WORKSPACE}/kernel"
          SUSFS="${GITHUB_WORKSPACE}/susfs4ksu"

          echo "Copying patch files…"

          # 1) Copy kernelSU patch → KernelSU folder
          cp $SUSFS/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch \
             $KERNEL_ROOT/KernelSU-Next/

          # 2) Copy kernel main patch → kernel root
          cp $SUSFS/kernel_patches/50_add_susfs_in_kernel-4.14.patch \
             $KERNEL_ROOT/

          # 3) Copy fs/ patches
          cp $SUSFS/kernel_patches/fs/* \
             $KERNEL_ROOT/fs/

          # 4) Copy include/linux patches
          cp $SUSFS/kernel_patches/include/linux/* \
             $KERNEL_ROOT/include/linux/

          echo "Patching KernelSU…"
          cd $KERNEL_ROOT/KernelSU-Next
          patch -p1 < 10_enable_susfs_for_ksu.patch || {
            echo "❌ KernelSU patch failed"
            # exit 1
          }

          echo "Patching kernel main patch…"
          cd $KERNEL_ROOT
          patch -p1 < 50_add_susfs_in_kernel-4.14.patch || {
            echo "❌ Main SUSFS patch had failures!"
            echo "You MUST manually fix conflicts!"
            # exit 1
          }

          echo "✅ SUSFS patching completed successfully!"

      - name: Collect .rej files
        if: always()   
        run: |
          mkdir -p rej-files
          find kernel -type f -name "*.rej" -exec cp --parents {} rej-files/ \; || true

      - name: Upload reject artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: patch-rejects
          path: rej-files
        
      - name: 📥 Clone AnyKernel3
        run: |
          cd kernel
          git clone -b master --depth=1 https://github.com/beingsk5/AnyKernel3.git anykernel
          rm -rf anykernel/.git
      - name: 🔍 Device's codename and kernel's version
        run: |
          cd kernel
          DEVICE_CODENAME=OnePlus-7-Series
          KERNEL_VERSION=$(make kernelversion)
          echo "Device Codename: $DEVICE_CODENAME"
          echo "Kernel Version: $KERNEL_VERSION"
          echo "DEVICE_CODENAME=$DEVICE_CODENAME" >> $GITHUB_ENV
          echo "KERNEL_VERSION=$KERNEL_VERSION" >> $GITHUB_ENV
        
      - name: 🛠️ Build the kernel
        run: |
          export KERNEL_DEFCONFIG="sm8150_defconfig"
          export KERNEL_CMDLINE="ARCH=arm64 CC=clang CROSS_COMPILE_COMPAT=aarch64-linux-android- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CLANG_TRIPLE=aarch64-linux-gnu- READELF=llvm-readelf LLVM_DIS=llvm-dis AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip LLVM=1 LLVM_IAS=1 LD=ld.lld HOSTCC=clang HOSTCXX=clang++ O=out"
          export PATH=$(pwd)/clang/bin/:$PATH
          export ARCH=arm64
          export SUBARCH=arm64
          export KBUILD_BUILD_USER="@beingsk5"
          export LD=ld.lld
          export BRAND_SHOW_FLAG=oneplus
          export TARGET_PRODUCT=msmnile
          cd kernel
          make $KERNEL_CMDLINE CC="ccache clang" $KERNEL_DEFCONFIG
          make $KERNEL_CMDLINE CC="ccache clang" Image modules -j$(nproc --all)
          
      - name: 🚀 Copy the compiled kernel to AnyKernel3 then create the zip
        run: |
          cd kernel

          ZIP_NAME="RagnaR-Kernel-${DEVICE_CODENAME}-${KERNEL_VERSION}-$(date +%d%m%Y).zip"

          cp -v out/arch/arm64/boot/Image anykernel/

          mkdir -p anykernel/modules/vendor/lib/modules/

          find out/ -type f -name "*.ko" | while IFS= read -r module; do
          filename=$(basename "$module")

          if [ "$filename" = "wlan.ko" ]; then
          echo "Renaming wlan.ko → qca_cld3_wlan.ko"
          cp -v "$module" anykernel/modules/vendor/lib/modules/qca_cld3_wlan.ko
          else
          cp -v "$module" anykernel/modules/vendor/lib/modules/
          fi
          done

          cd anykernel && zip -r9 $ZIP_NAME ./*

          mv $ZIP_NAME ../../

          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
          
      - name: 🤌 Copy zip file to get 2 different zip files
        run: |
          ZIP_ALTERNATIVE="KernelSu-Next-DERPFEST-RagnaR-${DEVICE_CODENAME}-latest.zip"
          cp ${ZIP_NAME} $ZIP_ALTERNATIVE
          echo "Copied ${ZIP_NAME} as $ZIP_ALTERNATIVE"
          echo "ZIP_ALTERNATIVE=$ZIP_ALTERNATIVE" >> $GITHUB_ENV
          
      - name: 📤 Publish github release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_ALTERNATIVE }}
          tag_name: "RagnaR-Kernel-latest"
          draft: false
          prerelease: false
          body: |
            Device: Oneplus 7 Series All Device Supported
            Target: DERPFEST A16

      - name: 📤 Publish with tag associated to the kernel and the date
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_NAME }}
          tag_name: RagnaR-Kernel-${{ env.DATE }}
          draft: false
          prerelease: false
          body: |
            Device: Oneplus 7 Series All Device Supported
            Target: DERPFEST A16
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
